config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/orders/big_orders', to: 'orders#big_orders'
    get '/invoice_items/most_ordered_item', to: 'invoice_items#most_ordered_item'

    resources :users

    resources :orders do
      resources :invoices
    end

    post 'users/:id/disable' => 'users#disable', as: :disable
    post 'users/:id/enable' => 'users#enable', as: :enable
    resources :orders
    resources :customers
    resources :employees
    resources :items
    resources :invoices
    root 'sessions#index'
    get '/signin', to: 'sessions#new', as: 'signin'
    post '/signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy', as: 'signout'
    get 'auth/:provider/callback', to: 'sessions#om_create'
    get 'auth/failure', to: redirect('/')





end

app/models/user.rb
class User < ApplicationRecord
  has_many :employees
  has_many :customers
  has_many :contacts


 has_secure_password
 validates :username, presence: true
 validates :username, uniqueness: true

 accepts_nested_attributes_for :contacts, update_only: true
 

 def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.username = auth.info.name
       user.password = "Auth temp pass"
       user.oauth_token = auth.credentials.token
       user.oauth_expires_at = Time.at(auth.credentials.expires_at)
       user.save!
     end
   end

 def user_number?
   if self.admin
    "EMP#{'%06d' % self.id}"
  else
    "CUS#{'%06d' % self.id}"
  end

 end

 def contact(user)
   Contact.find_by(:user_id=>user.id)
 end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  def new
    @user = User.new
    @user.contacts.build
  end
def show


    if !current_user.admin
      if current_salesman != @salesman
        redirect_to root_path
      end
    end
end
def edit
end
def create


  @user = User.new(user_params)
  if(@user.valid? and @user.save)
        flash[:notice] = "User created successfully"
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to action: "new"
    end

end

def update
  respond_to do |format|
    if @user.update(user_params)
      format.html { redirect_to @user, notice: 'User was successfully updated.' }
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      format.html { render :edit }
    end
  end
end

def destroy
  @user.destroy
  respond_to do |format|
    format.html { redirect_to user_url, notice: 'User was successfully destroyed.' }
  end
end


private

def user_params
  params.require(:user).permit(:user_name, :password, :password_confirmation)
end
def set_user
  @user = User.find(params[:id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def index


      @users = User.all

  end
  def most_orders

  end


  def new


    @user = User.new
    @user.contacts.build

  end
def show
  @user.contacts.build if @user.contacts.empty?
end
def edit

end
def create



  @user = User.new(user_params)

  if(@user.valid? and @user.save)
        if @user.admin
          employee = Employee.new
          employee.user_id = @user.id
          employee.user_number = @user.user_number?
          @user.user_number = @user.user_number?
          employee.save

          session[:employee_id] = employee.id
        else
          customer = Customer.new
          customer.user_id = @user.id
          customer.user_number = @user.user_number?
          @user.user_number = @user.user_number?
          customer.save
          session[:customer_id] = customer.id
        end

        flash[:notice] = "User created successfully"
        session[:user_id] = @user.id
        @user.save
        redirect_to user_path(@user)

    else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to action: "new"
    end

end

def update
  respond_to do |format|
    if @user.update(user_params)
      format.html { redirect_to @user, notice: 'User was successfully updated.' }
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      format.html { render :edit }
    end
  end
end

def destroy
  @user.destroy
  respond_to do |format|
    format.html { redirect_to user_url, notice: 'User was successfully destroyed.' }
  end
end

def disable

  @user = User.find_by(:id => params[:id])
  if @user.admin
    flash[:notice] = 'Yor are not able to disable a status of employees'
  else
    @user.update_column(:status, false)
  end

  redirect_to user_path(@user)

end
def enable

  @user = User.find_by(:id => params[:id])
  if @user.admin
    flash[:notice] = 'Yor are not able to disable a status of employees'
  else
    @user.update_column(:status, true)
  end

  redirect_to user_path(@user)
end


private

def user_params
  params.require(:user).permit(:username, :admin, :password, :password_confirmation, contacts_attributes: [:id, :name, :address_1, :address_2, :phone, :city, :state, :zip])
end
def set_user
  @user = User.find(params[:id])
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_customer.html.erb
<p>
<li><h5>Business Type: <%= customer.type %></h5> </li>
<li>Status: <%= customer.status %></li>
<p>

app/views/users/_employee.html.erb
  <p>
  <li><h5>Title: <%= employee.title %></h5> </li>
  <li>Status: <%= employee.status %></li>
  <p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>




  <div class="field"> <%= f.label :username %><br>
  <%= f.text_field :username %></div>
  <div class="field"><%= f.label :password %><br>
  <%= f.text_field :password %></div>
  <div class="field"><%= f.label :admin, value: "Check if you are an employee."  %>
  <%= f.check_box :admin%></div>

  <br>

  <h3>Contacts</h3>
  <div class="field"><%= f.fields_for :contacts do |contact| %>
      <%= contact.hidden_field(:user_id, :value => user.id)%>
        <p><li><%= contact.label :name, value: "Name: " %>
          <%= contact.text_field :name %></li>
          <li><%= contact.label :address_1, value: "Address 1: " %>
          <%= contact.text_field :address_1 %></li>
          <li><%= contact.label :address_2, value: "Address 2: " %>
          <%= contact.text_field :address_2 %></li>
          <li><%= contact.label :city, value: "City: " %>
          <%= contact.text_field :city %></li>
          <li><%= contact.label :state, value: "State: " %>
          <%= contact.text_field :state %></li>
          <li><%= contact.label :zip, value: "Zipcode: " %>
          <%= contact.text_field :zip %></li>
          <li><%= contact.label :phone, value: "Phone Number: " %>
          <%= contact.text_field :phone %></li>
        </p>
    <% end %>
    </div>




  <div class="actions"><%= f.submit 'Submit', :class => 'btn btn-primary' %></div>

<% end %>

app/views/users/_user.html.erb
<ul>

    <%if user.status == false%>
        <h4 style="color:red">Closed Account</h4>
    <%end%>
<p>
  <li><h5>Username: <%= user.username %></h5> </li>
  <li>User Number: <%= user.user_number %></li>

  <% user.contacts.each do |contact| %>
  <li>Name: <%=contact.name%></li>
  <li>Address 1: <%= contact.address_1%></li>
  <li>Address 2: <%= contact.address_2%></li>
  <li>City: <%= contact.city%></li>
  <li>State: <%= contact.state%></li>
  <li>Zipcode: <%= contact.zip%></li>

  <li>Phone Number: <%= contact.phone%></li>
  <%end%>
</p>
</ul>

app/views/users/edit.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Edit User</h1>

<%= render partial: "form", locals: { user:  @user } %>

</div>
</div>

app/views/users/index.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h3>User Lists</h3>
<p>Click <b style="color:green">Item Name</b> to see more details</p>
<% @users.each do |user| %>

        <li> <%= link_to "#{user.username}", user_path(user), {:class=> "w3-bar-item w3-button", :style=>"color:green; font-size:20px"}%>
          <%if user.admin %>
            employee
          <%else%>
          customer

          <%end%>


        </li>
        <br />


<% end %>




<% if current_user.admin %>
  <p><%= link_to "Add User", new_user_path, :class=> "w3-bar-item w3-button" %></p>
<%end%>
</div>
</div>

app/views/users/new.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Create User</h1>

<%= render partial: "form", locals: { user:  @user } %>
</div>
</div>

app/views/users/show.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h2>User Info</h2>

<%= render partial: "user", locals: {user: @user} %>
<div> <%= link_to "Edit User", edit_user_path(@user), :class=> "w3-bar-item w3-button"  %></div>
<% if current_user.admin %>

  <div>
  <% if @user.status %>
    <%= button_to "Disable User", disable_path, method: :post, :class=> "w3-bar-item w3-button"  %>
  <% else %>
    <%= button_to "Enable User", enable_path, method: :post, :class=> "w3-bar-item w3-button"  %>
  <%end%>
  </div>
<% end %>
</div>
</div>