config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/orders/big_orders', to: 'orders#big_orders'
    get '/invoice_items/most_ordered_item', to: 'invoice_items#most_ordered_item'

    resources :users

    resources :orders do
      resources :invoices
    end

    post 'users/:id/disable' => 'users#disable', as: :disable
    post 'users/:id/enable' => 'users#enable', as: :enable
    resources :orders
    resources :customers
    resources :employees
    resources :items
    resources :invoices
    root 'sessions#index'
    get '/signin', to: 'sessions#new', as: 'signin'
    post '/signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy', as: 'signout'
    get 'auth/:provider/callback', to: 'sessions#om_create'
    get 'auth/failure', to: redirect('/')





end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :customer
  belongs_to :employee
  has_many :invoices
  has_many :line_items
  has_many :items, -> { distinct }, through: :line_items
  validates :employee_id, :customer_id, presence: true

  accepts_nested_attributes_for :line_items, :allow_destroy => true, :reject_if => lambda { |c| c[:quantity].blank? }
  scope :ordered_employees, -> { group(:employee_id)}
  scope :ordered_customers, -> { group(:customer_id)}
  scope :totals, -> { group(:order_total)}
  scope :total_max, -> {order(:order_total, :desc) }
  scope :big_orders, -> {totals.total_max.limit(3)}


  before_validation do
  line_items.map do |l|

      item_ids = line_items.collect(&:item_id).compact
      item_ids_counted = item_ids.inject({}) { |hash,item_id| hash[item_id] = (hash[item_id] || 0) + 1; hash }
      duplicate_item_ids = item_ids_counted.select { |k,v| v > 1 }.keys
      l.instance_variable_set "@duplicate_item_ids", duplicate_item_ids

  end
end









  def sum
    total = 0

    if self.line_items.empty? != true
      self.line_items.each do |line_item|
        if !!line_item.quantity
          total = total + (line_item.item.price * line_item.quantity)
        end

      end

    else
      flash[:notice] = 'No orders'

    end



      total

  end





end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    before_action :set_order, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def big_orders

      @big_orders = Order.totals
      render 'big_orders'
    end
    def index
      @orders = Order.all
    end
    def new



      @order = Order.new

      if Order.all.empty?
        @order_number = "ORD#{'%06d' %  1 }"
      else
        @order_number = "ORD#{'%06d' % (Order.all.last.id + 1)}"
      end
    5.times do
           @order.line_items.build
         end
  end
  def show

    @order = Order.find(params[:id])
  end
  def edit
    @order_number = @order.order_num
  end
  def create


    @order = Order.new(order_params)

    if(@order.valid? and @order.save)


          flash[:notice] = "Order created successfully"

          redirect_to order_path(@order)

      else
          flash[:error] = @order.errors.full_messages.to_sentence
          redirect_to action: "new"
      end

  end

  def update

    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        flash[:error] = @order.errors.full_messages.to_sentence
        format.html { render :edit }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
    end
  end


  private

  def order_params
    params.require(:order).permit(:order_num, :order_total, :customer_id, :employee_id, line_items_attributes: [:id, :quantity, :order_id, :item_id])
  end
  def set_order
    @order = Order.find(params[:id])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>

<div> Order number: <%= @order_number %></div>
<%= f.hidden_field(:order_num, :value => "#{@order_number}")%>
 <div class="field"><%= f.label :employee_id, value: "Salesman: " %>
<%= f.collection_select(:employee_id, Employee.all, :id, :name) %></div>
<div class="field"><%= f.label :customer_id, value: "Customer: " %>
<%= f.collection_select(:customer_id, Customer.all, :id, :name) %></div>

<br />
<br/>
<table style="border-spacing: 5px;">

  <tr>
    <th>Item</th>
    <th>Quantity</th>
</tr>
<tr class="spacer"><td></td></tr>
      <%= f.fields_for :line_items do |line_item| %>

    <tr>

        <%= line_item.hidden_field(:order_id, :value => order.id)%>
        <td>
         <%= line_item.collection_select(:item_id, Item.all, :id, :name) %> </td>
        <td>
        <%= line_item.number_field :quantity %></td>
        

      </tr>
      <% end %>


<tr class="spacer"><td></td></tr>
</table>
  <div><%= f.submit 'Submit', :class => 'btn btn-primary' %></div>


<br /><br />

  <% end %>

app/views/orders/_order.html.erb
<ul>
<p>

  <li><h5>Order Number: <%= order.order_num %></h5> </li>
<li>Salesman: <%if order.employee.name != "" %> <%= order.employee.name %> <%else%><%= order.employee.user.username %><%end%></li>
<li>Customer: <%if order.customer.name != ""%> <%= order.customer.name %> <%else%><%= order.customer.user.username %><%end%></li>

<br />
  <li>Order List</li>

<table style="border-spacing: 12px;">

  <tr>
    <th>Item Name</th>
    <th>Quantity</th>
    <th>Sum</th>
</tr>



<tr class="spacer"><td></td></tr>
    <% order.line_items.each do |line_item| %>
    <% if !!line_item.quantity %>
      <tr>

        <td align="center">
          <%= line_item.item.name %>
         </td>
        <td align="center">
          <%= line_item.quantity %>
        </td>
        <td align="center">
          $<%= line_item.item.price * line_item.quantity%>
        </td>

      </tr>
      <% end %>
    <% end %>
    <tr class="spacer"><td></td></tr>
        <tr><td>Total : $<%= order.sum %></td> </tr>
</table>

app/views/orders/big_orders.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">


<h3>Big Orders</h3>
<p>Click <b style="color:green">Order Number</b> to see more details</p>
  <%@big_orders.each do |big_order| %>
    <li><%= link_to "#{big_order.order_num}", order_path(big_order), {:class=> "w3-bar-item w3-button", :style=>"color:green; font-size:20px"} %>,  $<%=big_order.order_total%></li>
  <%end%>



</div>
</div>

app/views/orders/bigest_order.html.erb
<%=Order.bigest_order%>HI

app/views/orders/edit.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Edit Order</h1>

<%= render partial: "form", locals: { order:  @order } %>

</div>
</div>

app/views/orders/index.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h3>Order Lists</h3>
<p>Click <b style="color:green">Order Number</b> to see more details</p>
<% @orders.each do |order| %>
        <%if current_user.id == order.customer.user_id || current_user.id == order.employee.user_id %>

        <li> <%= link_to "#{order.order_num}", order_path(order), {:class=> "w3-bar-item w3-button", :style=>"color:green; font-size:20px"}%>
            Salesman: <%if order.employee.name != "" %> <%= order.employee.name %> <%else%><%= order.employee.user.username %><%end%>, Customer: <%if order.customer.name != ""%> <%= order.customer.name %> <%else%><%= order.customer.user.username %><%end%></li>


        </li>


        <br />
        <%end%>

<% end %>

  <p><%= link_to "Add Order", new_order_path, :class=> "w3-bar-item w3-button" %></p>
<% if current_user.admin %>
  <p><%= link_to "See Big orders list", orders_big_orders_path, :class=> "w3-bar-item w3-button" %></p>
<% end %>

</div>
</div>

app/views/orders/new.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h2>Create Order</h2>
<%= render partial: "form", locals: { order:  @order } %>
</div>
</div>

app/views/orders/show.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">


<h2>Order Info</h2>

<%= render partial: "order", locals: {order: @order} %>
<br />


<%= link_to "Edit Order", edit_order_path(@order), :class=> "w3-bar-item w3-button"  %>


<% if current_user.admin%>

  <%= link_to "Create Invoice", new_order_invoice_path(@order), :class=> "w3-bar-item w3-button"  %>
<%end%>
</div>
</div>