config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/orders/big_orders', to: 'orders#big_orders'
    get '/invoice_items/most_ordered_item', to: 'invoice_items#most_ordered_item'

    resources :users

    resources :orders do
      resources :invoices
    end

    post 'users/:id/disable' => 'users#disable', as: :disable
    post 'users/:id/enable' => 'users#enable', as: :enable
    resources :orders
    resources :customers
    resources :employees
    resources :items
    resources :invoices
    root 'sessions#index'
    get '/signin', to: 'sessions#new', as: 'signin'
    post '/signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy', as: 'signout'
    get 'auth/:provider/callback', to: 'sessions#om_create'
    get 'auth/failure', to: redirect('/')





end

app/models/item.rb
class Item < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  has_many :invoice_items
  has_many :invoices, through: :invoice_items


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:edit, :update, :destroy, :new, :create]

  def index
    @items = Item.all
  end
  def new
    @item = Item.new

  end
def show

end
def edit
end
def create



  @item = Item.new(item_params)

  if(@item.valid? and @item.save)

        flash[:notice] = "Item created successfully"

        redirect_to item_path(@item)

    else
        flash[:error] = @item.errors.full_messages.to_sentence
        redirect_to action: "new"
    end

end

def update
  respond_to do |format|
    if @item.update(item_params)
      format.html { redirect_to @item, notice: 'Item was successfully updated.' }
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      format.html { render :edit }
    end
  end
end

def destroy
  @item.destroy
  respond_to do |format|
    format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
  end
end


private

def item_params
  params.require(:item).permit(:name, :item_type, :desc, :price, :inventory)
end
def set_item
  @item = Item.find(params[:id])
end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>




  <div class="field"> <%= f.label :name, :value => "Name: "  %><br>
  <%= f.text_field :name %></div>
  <div class="field"><%= f.label :item_type, :value => "Type: "  %><br>
  <%= f.text_field :item_type %></div>
  <div class="field"> <%= f.label :desc, :value => "Description: " %><br>
  <%= f.text_field :desc %></div>
  <div class="field"><%= f.label :price, :value => "Price: "  %><br>
  <%= f.number_field :price %></div>
  <div class="field"><%= f.label :inventory, :value => "Inventory: "  %><br>
  <%= f.number_field :inventory %></div>

  <br>





  <div class="actions"><%= f.submit 'Submit', :class => 'btn btn-primary' %></div>

<% end %>

app/views/items/_item.html.erb
<ul>
<p>

  <li><h5>Name: <%= item.name %></h5> </li>
  <li>Type: <%= item.item_type%></li>
  <li>Description: <%= item.desc%></li>
  <li>Price: $<%= item.price%></li>
  <li>Inventory: <%= item.inventory%></li>

</p>
</ul>

app/views/items/edit.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Edit Item</h1>

<%= render partial: "form", locals: { item:  @item } %>

</div>
</div>

app/views/items/index.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h3>Item Lists</h3>
<p>Click <b style="color:green">Item Name</b> to see more details</p>
<% @items.each do |item| %>

        <li> <%= link_to "#{item.name}", item_path(item), {:class=> "w3-bar-item w3-button", :style=>"color:green; font-size:20px"}%>
          <%= item.item_type %>, $<%= item.price %>

        </li>
        <br />


<% end %>
<% if current_user.admin %>
  <p><%= link_to "Add Item", new_item_path, :class=> "w3-bar-item w3-button" %></p>
<%end%>
</div>
</div>

app/views/items/new.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Create Item</h1>

<%= render partial: "form", locals: { item:  @item } %>
</div>
</div>

app/views/items/show.html.erb
<div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-left">

<h1>Item Info</h1>

<%= render partial: "item", locals: {item: @item} %>
<% if current_user.admin %>
  <p>
  <p><%= link_to "Add Item", new_item_path, :class=> "w3-bar-item w3-button"  %>
    <%= link_to "Edit Item", edit_item_path(@item), :class=> "w3-bar-item w3-button"  %>
     <%= link_to "Delete Item", item_path(@item), method: :delete, :class=> "w3-bar-item w3-button"  %></p>

<% end %>





</div>
</div>