config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/orders/big_orders', to: 'orders#big_orders'
    get '/invoice_items/most_ordered_item', to: 'invoice_items#most_ordered_item'

    resources :users

    resources :orders do
      resources :invoices
    end

    post 'users/:id/disable' => 'users#disable', as: :disable
    post 'users/:id/enable' => 'users#enable', as: :enable
    resources :orders
    resources :customers
    resources :employees
    resources :items
    resources :invoices
    root 'sessions#index'
    get '/signin', to: 'sessions#new', as: 'signin'
    post '/signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy', as: 'signout'
    get 'auth/:provider/callback', to: 'sessions#om_create'
    get 'auth/failure', to: redirect('/')





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  def self.find_by_user_id(user_id)
    self.all.detect {|s| user_id == s.user_id}
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :orders


  def self.find_by_user_id(user_id)
    self.all.detect {|s| user_id == s.user_id}
  end
  def contact(user)
    Contact.find_by(:user_id=>user.id)
  end
  def name
    Contact.find_by_user_id(self.user_id).name
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :orders

  def contact(user)
    Contact.find_by(:user_id=>user.id)
  end
  def name
    Contact.find_by_user_id(self.user_id).name
  end
  def self.find_by_user_id(user_id)
    self.all.detect {|s| user_id == s.user_id}
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
  belongs_to :order

  has_many :invoice_items
  has_many :items, through: :invoice_items

  accepts_nested_attributes_for :invoice_items, :allow_destroy => true





  def total
    result = 0

    if self.invoice_items.empty? != true
      self.invoice_items.each do |invoice_item|
        if !!invoice_item.shipped
          result = result + (invoice_item.item.price * invoice_item.shipped)
        end

      end

    else
      flash[:notice] = 'No orders'

    end



      result

  end



end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :item
  belongs_to :invoice


  scope :most_ordered_item, ->{
    group(:item_id).order('SUM(shipped) desc').limit(1);


  }



end

app/models/item.rb
class Item < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  has_many :invoice_items
  has_many :invoices, through: :invoice_items


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
    validate :ensure_unique_item_per_order

    def ensure_unique_item_per_order

        errors.add(:item_id, "duplicated item exists in order") if @duplicate_item_ids.present? and @duplicate_item_ids.include?(item_id)

     end


end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :customer
  belongs_to :employee
  has_many :invoices
  has_many :line_items
  has_many :items, -> { distinct }, through: :line_items
  validates :employee_id, :customer_id, presence: true

  accepts_nested_attributes_for :line_items, :allow_destroy => true, :reject_if => lambda { |c| c[:quantity].blank? }
  scope :ordered_employees, -> { group(:employee_id)}
  scope :ordered_customers, -> { group(:customer_id)}
  scope :totals, -> { group(:order_total)}
  scope :total_max, -> {order(:order_total, :desc) }
  scope :big_orders, -> {totals.total_max.limit(3)}


  before_validation do
  line_items.map do |l|

      item_ids = line_items.collect(&:item_id).compact
      item_ids_counted = item_ids.inject({}) { |hash,item_id| hash[item_id] = (hash[item_id] || 0) + 1; hash }
      duplicate_item_ids = item_ids_counted.select { |k,v| v > 1 }.keys
      l.instance_variable_set "@duplicate_item_ids", duplicate_item_ids

  end
end









  def sum
    total = 0

    if self.line_items.empty? != true
      self.line_items.each do |line_item|
        if !!line_item.quantity
          total = total + (line_item.item.price * line_item.quantity)
        end

      end

    else
      flash[:notice] = 'No orders'

    end



      total

  end





end

app/models/user.rb
class User < ApplicationRecord
  has_many :employees
  has_many :customers
  has_many :contacts


 has_secure_password
 validates :username, presence: true
 validates :username, uniqueness: true

 accepts_nested_attributes_for :contacts, update_only: true
 

 def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.username = auth.info.name
       user.password = "Auth temp pass"
       user.oauth_token = auth.credentials.token
       user.oauth_expires_at = Time.at(auth.credentials.expires_at)
       user.save!
     end
   end

 def user_number?
   if self.admin
    "EMP#{'%06d' % self.id}"
  else
    "CUS#{'%06d' % self.id}"
  end

 end

 def contact(user)
   Contact.find_by(:user_id=>user.id)
 end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  def new
    @user = User.new
    @user.contacts.build
  end
def show


    if !current_user.admin
      if current_salesman != @salesman
        redirect_to root_path
      end
    end
end
def edit
end
def create


  @user = User.new(user_params)
  if(@user.valid? and @user.save)
        flash[:notice] = "User created successfully"
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to action: "new"
    end

end

def update
  respond_to do |format|
    if @user.update(user_params)
      format.html { redirect_to @user, notice: 'User was successfully updated.' }
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      format.html { render :edit }
    end
  end
end

def destroy
  @user.destroy
  respond_to do |format|
    format.html { redirect_to user_url, notice: 'User was successfully destroyed.' }
  end
end


private

def user_params
  params.require(:user).permit(:user_name, :password, :password_confirmation)
end
def set_user
  @user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <title>SalesdirectorV2</title>

  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script type="text/javascript">

  // Accordion
  function myAccFunc() {
      var x = document.getElementById("demoAcc");
      if (x.className.indexOf("w3-show") == -1) {
          x.className += " w3-show";
      } else {
          x.className = x.className.replace(" w3-show", "");
      }
  }

  // Click on the "Jeans" link on page load to open the accordion for demo purposes
  document.getElementById("myBtn1").click();
  document.getElementById("myBtn2").click();
  document.getElementById("myBtn3").click();
  document.getElementById("myBtn4").click();


  // Script to open and close sidebar
  function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
      document.getElementById("myOverlay").style.display = "block";
  }

  function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
      document.getElementById("myOverlay").style.display = "none";
  }
  </script>


<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
div {
    margin: 0px;
    padding: 0px;
}
table {
    margin: 0px;
    border-collapse: collapse;
    padding: 0px;
}
</style>

<body class="w3-content" style="max-width:1200px">
  <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" style="color:red; position:relative; overflow:hidden;z-index: 100"><%= value %></div>
        <% end %>
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px;" id="mySidebar">
  <div class="w3-container w3-display-container w3-padding-16">
    <% if logged_in? %>
    <h4> <%= link_to "#{current_user.username}'s Profile", user_path(current_user), :class=> "w3-bar-item w3-button"%></h4>
    <% else %>
    <h4 class="w3-wide"><b>Sales Director</b></h4>
    <%end%>

  </div>
  <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">



  <% if logged_in? %>
    <%= link_to 'Order Now', new_order_path, :class=> "w3-bar-item w3-button", :style=>"color:blue" %>

    <%= link_to 'Orders ', orders_path, :class=> "w3-bar-item w3-button" %>
    <%= link_to 'Items ', items_path, :class=> "w3-bar-item w3-button" %>
    <% if current_user.admin %>
      <%= link_to 'Invoices', invoices_path, :class=> "w3-bar-item w3-button" %>
      <%= link_to 'Customers', customers_path, :class=> "w3-bar-item w3-button" %>
      <%= link_to 'Users', users_path, :class=> "w3-bar-item w3-button" %>

    <%end%>
  <%end%>

  </div>
  <%= link_to 'Home', root_path, :class=> "w3-bar-item w3-button w3-padding"%>
  <% if !logged_in? %>
    <%= link_to 'Sign Up ', new_user_path, :class=> "w3-bar-item w3-button w3-padding" %>
    <%= link_to 'Sign In', signin_path, :class=> "w3-bar-item w3-button w3-padding"%>
    <div class= "w3-bar-item w3-button w3-padding">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>

  <% else %>
    <%= link_to 'Sign Out', signout_path, method: :delete, :class=> "w3-bar-item w3-button w3-padding" %>
  <%end%>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>


  <%= yield %>

  <!-- End page content -->
</div>



</body>
</html>